apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  auth:
    strategy: anonymous  # or "login" for real security
  server:
    address: ":20001"
  istio_namespace: istio-system
  deployment:
    namespace: istio-system
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
