{{- if .Values.enableGatekeeper }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: require-app-label
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    labels: ["app"]
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedRepos
metadata:
  name: only-approved-image-registries
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    repos: ["myregistry.io/", "docker.io/official/"]
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sNoPrivContainers
metadata:
  name: no-privileged-containers
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPSELinux
metadata:
  name: enforce-selinux
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    rule: "MustRunAs"
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedCapabilities
metadata:
  name: allowed-capabilities
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedCapabilities: ["NET_BIND_SERVICE"]
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPHostNetwork
metadata:
  name: disallow-host-network
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedHostNetwork: false
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedVolumes
metadata:
  name: restrict-volume-types
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedVolumes: ["configMap", "emptyDir", "secret", "persistentVolumeClaim"]
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequireCpuMemory
metadata:
  name: require-resource-limits
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    cpuLimitRequired: true
    memoryLimitRequired: true
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDenyEscalatingExec
metadata:
  name: deny-escalating-exec
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet", "DaemonSet"]
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sContainerLimits
metadata:
  name: limit-pod-cpu-mem
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    maxCPU: "2"
    maxMemory: "2Gi"
{{- end }}
